language: bash
before_deploy: pip install --user awscli
deploy:
  # sync files to S3 from Jekyll build in `_site` directory
  provider: script
  script: ~/.local/bin/aws s3 sync _site s3://srccon.org --region=$AWS_DEFAULT_REGION --delete
  skip_cleanup: true
  # only deploy on new commits to `master` branch
  on:
    branch: master
after_deploy:
  # after the build, connect to Cloudfront and invalidate all the cached objects
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"