name: SRCCON
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
plugins:
  - jekyll-redirect-from
exclude: ['*.yml']
collections:
  transcripts:
    output: true
    permalink: /:collection/:title/
  share:
    output: true
    permalink: /:collection/:slug/

defaults:
  - scope:
      path: ""
    values:
      layout: layout_hub
      title: SRCCON Events — Change how your journalism works
      description: SRCCON events are participatory, interactive conferences and workshops centered on the challenges that news technology and data teams encounter every day.
  - scope:
      path: ""
      type: "transcripts"
    values:
      layout: layout
      section: remote
  - scope:
      path: ""
      type: "share"
    values:
      layout: layout_hub
      section: share
      description: Exercises and tipsheets to help you get the most out of a journalism event, then share what you learned when you get back home.