name: SRCCON
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
gems:
  - jekyll-redirect-from
exclude: ['*.yml']
collections:
  transcripts:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: "transcripts"
    values:
      layout: layout
      section: remote