name: Deploy to S3

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    uses: OpenNews/opennews-actions/.github/workflows/jekyll-deploy.yml@v1
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication
      deployments: write # Required for GitHub Deployments API
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
